---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-nfs-subdir-external-provisioner
commonLabels:
  app: nfs-subdir-external-provisioner

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: nfs
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
<<<<<<< before updating

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
- resources/storage-classes.yaml
=======
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: nfs
      namespace: nfs
      annotations:
        gethomepage.dev/href: https://nfs.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: nfs
        gethomepage.dev/name: nfs
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
>>>>>>> after updating
